### ISSUE TITLE
Adding 1wire support

### ISSUE THREAD

**Issue by iganin67** [linuxserver/docker-domoticz#62]
Dear,

Is it feasible to add 1wire support to the container.

Thank you a lot in advance.

Kind Regards,
Ihor Hanin

**Comment by tobbenb** [comment]
Sorry for the late reply.
I'm not sure how this can be implemented in this container. The domoticz page for 1wire mention two kernel modules need to be compiled. This must be done on the host system and I don't know how to pass that through to the container. If the it's attached as a device, I guess it can be passed through using the --device= tag, but otherwise I'm not sure how to do it.

After looking a little bit more about owfs, I think this is better installed on the host than in the container. Then you just bind mount the owfs filesystem to the container. And it will hopefully work.

**Comment by tobbenb** [comment]
Closing this due to no response.
