### ISSUE TITLE
Add EXPOSE to Dockerfile

### ISSUE THREAD

**Issue by Frank071** [linuxserver/docker-domoticz#94]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Desired Behavior
Expose the domoticz ports explicitly (by adding EXPOSE keyword to Docker file)

## Current Behavior
Ever since I installed watchtowerrr the linuxserver/domoticz container dies on an (automatic) update. After some investigation it might be that this is caused by the image to have ports bound, but not exposed. See https://github.com/containrrr/watchtower/issues/832
Looking at differences between this and other linuxserver containers, I found that the domoticz image does not have an EXPOSE keyword in the Dockerfile. From the docker documentation I gather this means that ports are made available, but not published. This might be the culprit.

## Alternatives Considered
Perhaps there is good reason for not having that EXPOSE line in the Dockerfile. Please let me know.

**Comment by tobbenb** [comment]
You need to map the ports in the run command or in your compose, unless you run the container in a custome bridge and reverse proxy it. That is documented in the readme.
The EXPOSE is mostly for documenting the ports and doesn't do anything really.

I would recommend not using watchtower as it just blindly updates your containers.

**Comment by Frank071** [comment]
I knew it wasn't a good idea to mention watchtowerrr.... Let's drop that bit. My suggestion is simply to add the ports as EXPOSE lines as the directive is mentioned in the Docker Best Practices. Other linuxserver containers use this directive in a similar context.

**Comment by simonaronsson** [comment]
@tobbenb 

> The EXPOSE is mostly for documenting the ports and doesn't do anything really.

Isn't documentation as good a reason as any? It also allows users to write automation that relies on the metadata. It's even mentioned in docker's own Dockerfile best practices:  https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

> as it just blindly updates your containers.

I know your general stance as a project is to discourage automation for some reason, but this statement is not entirely true. Lifecycle hooks have been available for well over a year now, allowing users to add conditional logic both prior to checking for images and prior to recreating the container.

**Comment by thespad** [comment]
We don't discourage automation, we discourage the blind setting-and-forgetting of automatic updates which cause us support issues when containers randomly die after 6 months and the user has no backups and no idea how they originally set it up. If you know enough to safely automate your docker infrastucture, go nuts.

Some tools do rely on the EXPOSE satement but it's a bad idea to do so because a) it's not mandatory and b) there's no standard for the order of listed ports in the case that there's more than one, no way to list ports as optional, and no means to determine their function. While the -P (not -p) argument for the docker CLI does exist it's virtually unused because it binds each EXPOSEd port to a random port on the host, which is rarely useful.

You're welcome to submit a PR to add the EXPOSE statements into the Dockerfiles but I wouldn't consider it an Issue per se.

**Comment by Frank071** [comment]
> You're welcome to submit a PR to add the EXPOSE statements into the Dockerfiles but I wouldn't consider it an Issue per se.

I think I already suggested a (very simple) change to that file...
